name: Unit test
on:
  push: {}
  workflow_dispatch: {}
jobs:
  test:
    name: unit test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.2'
      - name: run test
        run: make test
